import { request } from "../lib/datocms";
import { useQuerySubscription } from "react-datocms";
import GET_HOME from "operations/queries/getHome";
import classNames from "classnames";
import CardList from "@components/CardList";
import Layout from "core/Layout";
import dynamic from "next/dynamic";

export async function getStaticProps() {
  const data = await request({
    query: GET_HOME,
    variables: { limit: 10 },
  });
  return {
    props: { data },
  };
}

const components = {
  // global_navigation: {
  //   comp: dynamic(() => import('../components/Global/GlobalNavigation')),
  //   mapping: require('../components/Global/GlobalNavigation/mapping'),
  // },
  // hero: {
  //   comp: dynamic(() => import('../components/Hero')),
  //   mapping: require(`../components/Hero/mapping`),
  // },
  // promo: {
  //   comp: dynamic(() => import('../components/Promo')),
  //   mapping: require(`../components/Promo/mapping`),
  // },

  card_list: {
    comp: dynamic(() => import("../components/CardList")),
    // mapping: require(`../components/CardList/mapping`),
  },
  // demosection: {
  //   comp: dynamic(() => import("../components/DemoSection")),
  //   mapping: require(`../components/DemoSection/mapping`),
  // },
  // global_footer: {
  //   comp: dynamic(() => import('../components/Global/GlobalFooter')),
  //   mapping: require('../components/Global/GlobalFooter/mapping'),
  // },
};

const renderComponents = (data) => {
  const components = data?.map((component) => {
    switch (component?._modelApiKey) {
      case "card_list":
        return <CardList data={component} />;
        break;
        break;
      default:
        null;
    }
  });
  return components;
};

export default function Home({ data }) {
  const {
    home: { components: bodyComponents },
    // _site,
    // globalNavigation,
    // globalFooter,
  } = data;

  return (
    <div>
      <Layout components={components} data={[...bodyComponents]}>
        <main>
          <h3>Dato Next App</h3>{" "}
          {/* <h9>{JSON.stringify(data, null, 2)}</h9> */}
          {...renderComponents(bodyComponents)}
        </main>
      </Layout>
    </div>
  );
}
// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={`${styles.main} ${inter.className}`}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>pages/index.js</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>

//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   )
// }
